from __future__ import annotations

from .optimizer import Graph, Station, normalize


LineStop = tuple[str, tuple[str, ...]]


LINES: dict[str, list[LineStop]] = {
    "North South Line": [
        ("Jurong East", ("NS1", "EW24")),
        ("Bukit Batok", ("NS2",)),
        ("Bukit Gombak", ("NS3",)),
        ("Choa Chu Kang", ("NS4",)),
        ("Yew Tee", ("NS5",)),
        ("Kranji", ("NS7",)),
        ("Marsiling", ("NS8",)),
        ("Woodlands", ("NS9", "TE2")),
        ("Admiralty", ("NS10",)),
        ("Sembawang", ("NS11",)),
        ("Canberra", ("NS12",)),
        ("Yishun", ("NS13",)),
        ("Khatib", ("NS14",)),
        ("Yio Chu Kang", ("NS15",)),
        ("Ang Mo Kio", ("NS16",)),
        ("Bishan", ("NS17", "CC15")),
        ("Braddell", ("NS18",)),
        ("Toa Payoh", ("NS19",)),
        ("Novena", ("NS20",)),
        ("Newton", ("NS21", "DT11")),
        ("Orchard", ("NS22", "TE14")),
        ("Somerset", ("NS23",)),
        ("Dhoby Ghaut", ("NS24", "NE6", "CC1")),
        ("City Hall", ("NS25", "EW13")),
        ("Raffles Place", ("NS26", "EW14")),
        ("Marina Bay", ("NS27", "CE2", "TE20")),
        ("Marina South Pier", ("NS28",)),
    ],
    "East West Line": [
        ("Pasir Ris", ("EW1",)),
        ("Tampines", ("EW2", "DT32")),
        ("Simei", ("EW3",)),
        ("Tanah Merah", ("EW4",)),
        ("Bedok", ("EW5",)),
        ("Kembangan", ("EW6",)),
        ("Eunos", ("EW7",)),
        ("Paya Lebar", ("EW8", "CC9")),
        ("Aljunied", ("EW9",)),
        ("Kallang", ("EW10",)),
        ("Lavender", ("EW11",)),
        ("Bugis", ("EW12", "DT14")),
        ("City Hall", ("NS25", "EW13")),
        ("Raffles Place", ("NS26", "EW14")),
        ("Tanjong Pagar", ("EW15",)),
        ("Outram Park", ("EW16", "NE3", "TE17")),
        ("Tiong Bahru", ("EW17",)),
        ("Redhill", ("EW18",)),
        ("Queenstown", ("EW19",)),
        ("Commonwealth", ("EW20",)),
        ("Buona Vista", ("EW21", "CC22")),
        ("Dover", ("EW22",)),
        ("Clementi", ("EW23",)),
        ("Jurong East", ("NS1", "EW24")),
        ("Chinese Garden", ("EW25",)),
        ("Lakeside", ("EW26",)),
        ("Boon Lay", ("EW27",)),
        ("Pioneer", ("EW28",)),
        ("Joo Koon", ("EW29",)),
        ("Gul Circle", ("EW30",)),
        ("Tuas Crescent", ("EW31",)),
        ("Tuas West Road", ("EW32",)),
        ("Tuas Link", ("EW33",)),
    ],
    "Changi Airport Branch": [
        ("Tanah Merah", ("EW4",)),
        ("Expo", ("CG1", "DT35")),
        ("Changi Airport", ("CG2",)),
    ],
    "North East Line": [
        ("HarbourFront", ("NE1", "CC29")),
        ("Outram Park", ("EW16", "NE3", "TE17")),
        ("Chinatown", ("NE4", "DT19")),
        ("Clarke Quay", ("NE5",)),
        ("Dhoby Ghaut", ("NS24", "NE6", "CC1")),
        ("Little India", ("NE7", "DT12")),
        ("Farrer Park", ("NE8",)),
        ("Boon Keng", ("NE9",)),
        ("Potong Pasir", ("NE10",)),
        ("Woodleigh", ("NE11",)),
        ("Serangoon", ("NE12", "CC13")),
        ("Kovan", ("NE13",)),
        ("Hougang", ("NE14",)),
        ("Buangkok", ("NE15",)),
        ("Sengkang", ("NE16",)),
        ("Punggol", ("NE17",)),
        ("Punggol Coast", ("NE18",)),
    ],
    "Circle Line": [
        ("Dhoby Ghaut", ("NS24", "NE6", "CC1")),
        ("Bras Basah", ("CC2",)),
        ("Esplanade", ("CC3",)),
        ("Promenade", ("CC4", "DT15")),
        ("Nicoll Highway", ("CC5",)),
        ("Stadium", ("CC6",)),
        ("Mountbatten", ("CC7",)),
        ("Dakota", ("CC8",)),
        ("Paya Lebar", ("EW8", "CC9")),
        ("MacPherson", ("CC10", "DT26")),
        ("Tai Seng", ("CC11",)),
        ("Bartley", ("CC12",)),
        ("Serangoon", ("NE12", "CC13")),
        ("Lorong Chuan", ("CC14",)),
        ("Bishan", ("NS17", "CC15")),
        ("Marymount", ("CC16",)),
        ("Caldecott", ("CC17", "TE9")),
        ("Botanic Gardens", ("CC19", "DT9")),
        ("Farrer Road", ("CC20",)),
        ("Holland Village", ("CC21",)),
        ("Buona Vista", ("EW21", "CC22")),
        ("one-north", ("CC23",)),
        ("Kent Ridge", ("CC24",)),
        ("Haw Par Villa", ("CC25",)),
        ("Pasir Panjang", ("CC26",)),
        ("Labrador Park", ("CC27",)),
        ("Telok Blangah", ("CC28",)),
        ("HarbourFront", ("NE1", "CC29")),
    ],
    "Circle Line Extension": [
        ("Promenade", ("CC4", "DT15")),
        ("Bayfront", ("CE1", "DT16")),
        ("Marina Bay", ("NS27", "CE2", "TE20")),
    ],
    "Downtown Line": [
        ("Bukit Panjang", ("DT1",)),
        ("Cashew", ("DT2",)),
        ("Hillview", ("DT3",)),
        ("Hume", ("DT4",)),
        ("Beauty World", ("DT5",)),
        ("King Albert Park", ("DT6",)),
        ("Sixth Avenue", ("DT7",)),
        ("Tan Kah Kee", ("DT8",)),
        ("Botanic Gardens", ("CC19", "DT9")),
        ("Stevens", ("DT10", "TE11")),
        ("Newton", ("NS21", "DT11")),
        ("Little India", ("NE7", "DT12")),
        ("Rochor", ("DT13",)),
        ("Bugis", ("EW12", "DT14")),
        ("Promenade", ("CC4", "DT15")),
        ("Bayfront", ("CE1", "DT16")),
        ("Downtown", ("DT17",)),
        ("Telok Ayer", ("DT18",)),
        ("Chinatown", ("NE4", "DT19")),
        ("Fort Canning", ("DT20",)),
        ("Bencoolen", ("DT21",)),
        ("Jalan Besar", ("DT22",)),
        ("Bendemeer", ("DT23",)),
        ("Geylang Bahru", ("DT24",)),
        ("Mattar", ("DT25",)),
        ("MacPherson", ("CC10", "DT26")),
        ("Ubi", ("DT27",)),
        ("Kaki Bukit", ("DT28",)),
        ("Bedok North", ("DT29",)),
        ("Bedok Reservoir", ("DT30",)),
        ("Tampines West", ("DT31",)),
        ("Tampines", ("EW2", "DT32")),
        ("Tampines East", ("DT33",)),
        ("Upper Changi", ("DT34",)),
        ("Expo", ("CG1", "DT35")),
    ],
    "Thomson-East Coast Line": [
        ("Woodlands North", ("TE1",)),
        ("Woodlands", ("NS9", "TE2")),
        ("Woodlands South", ("TE3",)),
        ("Springleaf", ("TE4",)),
        ("Lentor", ("TE5",)),
        ("Mayflower", ("TE6",)),
        ("Bright Hill", ("TE7",)),
        ("Upper Thomson", ("TE8",)),
        ("Caldecott", ("CC17", "TE9")),
        ("Stevens", ("DT10", "TE11")),
        ("Napier", ("TE12",)),
        ("Orchard Boulevard", ("TE13",)),
        ("Orchard", ("NS22", "TE14")),
        ("Great World", ("TE15",)),
        ("Havelock", ("TE16",)),
        ("Outram Park", ("EW16", "NE3", "TE17")),
        ("Maxwell", ("TE18",)),
        ("Shenton Way", ("TE19",)),
        ("Marina Bay", ("NS27", "CE2", "TE20")),
        ("Gardens by the Bay", ("TE22",)),
        ("Tanjong Rhu", ("TE23",)),
        ("Katong Park", ("TE24",)),
        ("Tanjong Katong", ("TE25",)),
        ("Marine Parade", ("TE26",)),
        ("Marine Terrace", ("TE27",)),
        ("Siglap", ("TE28",)),
        ("Bayshore", ("TE29",)),
    ],
}

LINE_GROUPS = {
    "Changi Airport Branch": "East West Line",
    "Circle Line Extension": "Circle Line",
}


def build_graph() -> Graph:
    graph = Graph()
    for stops in LINES.values():
        for name, codes in stops:
            graph.add_station(Station(id=normalize(name), name=name, codes=codes))

    for line_name, stops in LINES.items():
        line = LINE_GROUPS.get(line_name, line_name)
        for (left_name, _), (right_name, _) in zip(stops, stops[1:]):
            graph.connect(normalize(left_name), normalize(right_name), line=line)

    return graph
